#!/usr/bin/env node
/*
 * Emits the standalone scripts to paste into the Figma MCP `use_figma` tool.
 *
 *   node design/figma-brochure/generate.js
 *
 * Output (design/figma-brochure/out/):
 *   00-discover.js   read-only audit: pages, image hashes, fonts, existing frames
 *   01-setup.js      creates the target Figma page
 *   page-01.js ...   one build script per spread (keeps each call under the
 *                    ~10-operations-per-call guidance and makes failures cheap)
 *
 * Run them in order. Each returns the node ids it created so the next call can
 * reference them, and page-NN scripts are independent — a failed one can be
 * re-run on its own without touching the others.
 */

const fs = require('fs');
const path = require('path');

const { TYPE, COLOR } = require('./tokens.cjs');
const { PAGES, IMAGE_SLOTS } = require('./deck.cjs');

const OUT = path.join(__dirname, 'out');
const RENDERER = fs.readFileSync(path.join(__dirname, 'renderer.js'), 'utf8');

const TARGET_PAGE = 'Brochure — Reference Rebuild';
const COL_PITCH = 1440; // artboard 1240 + 200 gutter
const ROW_PITCH = 1954;

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

const header = (title) => `/* ${title}
 * Generated by design/figma-brochure/generate.js — do not hand-edit; edit deck.cjs
 * or tokens.cjs and regenerate.
 */\n`;

/* 00 — discovery ----------------------------------------------------------- */
fs.writeFileSync(path.join(OUT, '00-discover.js'), header('Read-only audit of the Figma file') + `
const pages = figma.root.children.map((p) => ({ id: p.id, name: p.name, children: p.children.length }));

// Harvest every raster already in the file so the rebuild can reuse the real
// photography instead of the reference's grey placeholders.
const seen = new Map();
for (const n of figma.currentPage.findAll((n) => 'fills' in n && Array.isArray(n.fills))) {
  for (const f of n.fills) {
    if (f.type !== 'IMAGE' || !f.imageHash) continue;
    if (!seen.has(f.imageHash)) {
      seen.set(f.imageHash, { hash: f.imageHash, usedBy: [], w: Math.round(n.width), h: Math.round(n.height) });
    }
    seen.get(f.imageHash).usedBy.push(n.name + ' (' + n.id + ')');
  }
}

const fonts = await figma.listAvailableFontsAsync();
const families = ['Marcellus', 'Arimo', 'Courier New', 'Cormorant Garamond', 'EB Garamond', 'Roboto Mono'];
const fontReport = {};
for (const fam of families) {
  fontReport[fam] = fonts.filter((f) => f.fontName.family === fam).map((f) => f.fontName.style);
}

const collections = await figma.variables.getLocalVariableCollectionsAsync();
const vars = [];
for (const c of collections) {
  for (const id of c.variableIds) {
    const v = await figma.variables.getVariableByIdAsync(id);
    if (v) vars.push({ id: v.id, name: v.name, type: v.resolvedType, collection: c.name });
  }
}

return {
  currentPage: { id: figma.currentPage.id, name: figma.currentPage.name },
  pages,
  imagesOnCurrentPage: [...seen.values()],
  fonts: fontReport,
  variables: vars,
  imageSlotsNeeded: ${JSON.stringify(IMAGE_SLOTS)},
};
`);

/* 01 — create the target page --------------------------------------------- */
fs.writeFileSync(path.join(OUT, '01-setup.js'), header('Create the rebuild page') + `
let page = figma.root.children.find((p) => p.name === ${JSON.stringify(TARGET_PAGE)});
if (!page) {
  page = figma.createPage();
  page.name = ${JSON.stringify(TARGET_PAGE)};
}
await figma.setCurrentPageAsync(page);
return { pageId: page.id, name: page.name, existingChildren: page.children.length };
`);

/* page-NN — one spread each ------------------------------------------------ */
PAGES.forEach((page, i) => {
  const origin = { x: (i % 5) * COL_PITCH, y: Math.floor(i / 5) * ROW_PITCH };
  const file = `page-${String(i + 1).padStart(2, '0')}.js`;

  fs.writeFileSync(path.join(OUT, file), header(`Build spread — ${page.name}`) + `
const STYLES  = ${JSON.stringify(TYPE, null, 2)};
const PALETTE = ${JSON.stringify(COLOR, null, 2)};

/* Fill this in from 00-discover.js: { slotName: 'imageHash', ... }
 * Slots left out fall back to the reference's flat plate + caption. */
const IMAGES = {};

const PAGE_SPEC = ${JSON.stringify(page, null, 2)};

${RENDERER}

const target = figma.root.children.find((p) => p.name === ${JSON.stringify(TARGET_PAGE)});
if (!target) throw new Error('Run 01-setup.js first — page ${JSON.stringify(TARGET_PAGE)} does not exist');
await figma.setCurrentPageAsync(target);

// Rebuilding is idempotent: drop any previous version of this spread first.
const stale = target.children.filter((c) => c.name === PAGE_SPEC.name);
for (const s of stale) s.remove();

return await buildPage(PAGE_SPEC, STYLES, PALETTE, IMAGES, ${JSON.stringify(origin)});
`);
});

const written = fs.readdirSync(OUT).sort();
console.log(`Wrote ${written.length} scripts to ${path.relative(process.cwd(), OUT)}/`);
for (const f of written) {
  const bytes = fs.statSync(path.join(OUT, f)).size;
  console.log(`  ${f.padEnd(16)} ${String(bytes).padStart(6)} bytes`);
}
